version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: ./backend/backend.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb+srv://karlmarxroxas1:Mvckf9rVcnZoxP0V@website.h8t2kwr.mongodb.net/ecotopia

  frontend:
    build:
      context: .
      dockerfile: /frontend.Dockerfile
    ports:
      - "4200:4200"
